services:
  backend:
    container_name: backend-socialize-secure
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "${APP_PORT}:${APP_PORT}"
    networks:
      - socialize-networks
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:${APP_PORT}/health-check"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mariadb:11.0
    container_name: db-socialize-secure
    environment:
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=0
      - MARIADB_ROOT_PASSWORD=${DB_PASSWORD}
      - MARIADB_DATABASE=${DB_NAME}
      - MARIADB_USER=${DB_USER}
      - MARIADB_PASSWORD=${DB_PASSWORD}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - socialize-networks
    restart: always
    healthcheck:
      test:
        [
          "CMD",
          "mariadb-admin",
          "ping",
          "-h",
          "localhost",
          "-u",
          "${DB_USER}",
          "-p${DB_PASSWORD}",
        ]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mariadb_data:

networks:
  socialize-networks:
    driver: bridge
