services:
  backend:
    container_name: backend-socialize-vulnerable
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8061:8061"
    networks:
      - socialize-networks
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8061/health-check"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mariadb:11.0
    container_name: db-socialize-vulnerable
    environment:
      - MARIADB_ROOT_PASSWORD=
      - MARIADB_ALLOW_EMPTY_ROOT_PASSWORD=1
      - MARIADB_DATABASE=db-socialize
      - MARIADB_EXTRA_FLAGS=--skip-grant-tables
    ports:
      - "3307:3306"
    volumes:
      - mariadb_data:/var/lib/mysql
    networks:
      - socialize-networks
    restart: always
    healthcheck:
      test: ["CMD", "mariadb-admin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mariadb_data:

networks:
  socialize-networks:
    driver: bridge
