services:
  backend:
    container_name: backend-socialize-vulnerable
    build:
      context: .
      dockerfile: Dockerfile
    restart: always
    ports:
      - "8060:8060"
    networks:
      - socialize-networks
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8060"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8
    container_name: db-socialize-vulnerable
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=""
      - MYSQL_DATABASE=db-socialize
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - socialize-networks
    restart: always
    command: ["mysqld", "--mysql-native-password=ON"]
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:

networks:
  socialize-networks:
    driver: bridge
