services:
  backend:
    container_name: backend-socialize
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:80"
      - "443:443"
    networks:
      - socialize-networks
    depends_on:
      - db
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:80"]
      interval: 30s
      timeout: 10s
      retries: 5

  db:
    image: mysql:8
    container_name: database-socialize
    env_file:
      - ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=socialize
      - MYSQL_DATABASE=socialize_db
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - socialize-networks
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 5

volumes:
  mysql_data:

networks:
  socialize-networks:
    driver: bridge
