pipeline {
    agent any

    environment {
        DOCKER_COMPOSE_FILE = "docker-compose.yaml"
        TARGET_URL = "http://localhost:8060"
        SONARQUBE_INSTALLATION = "sonarqube"  
        scannerHome = tool 'sonarqube-scanner' 
    }

    stages {
        stage ('Preparation') {
            steps {
                sh """
                    docker --version
                    docker compose version
                    curl --version
                    ${scannerHome}/bin/sonar-scanner --version
                """
            }
        }
        
        stage('Clone Repository') {
            steps {
                script {
                    echo 'Cloning Repository...'
                }
                git branch: 'vulnerable', url: 'https://github.com/federicodosantos/socialize-be.git'
            }
        }

        stage('SonarQube Analysis') {
            steps {
                echo 'Starting SonarQube analysis...'
                withSonarQubeEnv(SONARQUBE_INSTALLATION) {
                    script {
                        sh """
                            ${scannerHome}/bin/sonar-scanner \
                            -Dsonar.projectKey=socialize-be-vulnerable \
                        """
                    }
                }
            }
        }

        stage('Remove Containers') {
            steps {
                sh 'docker compose -f $DOCKER_COMPOSE_FILE down || true'
            }
        }

        stage('Running Containers') {
            steps {
                echo 'Building Docker image...'
                sh 'docker compose -f $DOCKER_COMPOSE_FILE up --detach --build'
                sh 'docker compose ps'
            }
        }

    }

    post {
        failure {
            echo 'Pipeline failed!'
        }
        success {
            echo 'Pipeline completed successfully!'
        }
    }
}
